[general]
import = [
    "theme.toml"
    ]

[window.dimensions]
columns = 90
lines = 30

[window.padding]
x = 3
y = 3

[cursor]
style = "Beam"
unfocused_hollow = true

[font]
size = 14

[font.bold]
family = "Cascadia Mono NF"
style = "Bold"

[font.italic]
family = "Cascadia Mono NF"
style = "Italic"

[font.normal]
family = "Cascadia Mono NF"
style = "Regular"

[selection]
save_to_clipboard = true

[terminal]
shell = "zsh"
