[window]
opacity = 0.9

[window.dimensions]
columns = 90
lines = 30

[window.padding]
x = 3
y = 3

[cursor]
style = "Beam"
unfocused_hollow = true

[font]
size = 12

[font.normal]
family = "OpenDyslexicMono Nerd Font"
style = "Regular"

[selection]
save_to_clipboard = true

[terminal]
shell = "zsh"
